### ISSUE TITLE
Usage in runtime in tests instead of compilation time

### ISSUE THREAD

**Issue by elpddev** [sinetris/factory_girl_elixir#4]
Hi,
Is the declaring of the factory module should only happen inside the test itself ? From what I gather, the declaration of the factory methods are done into a genserver which is initialized with the application at runtime.

**Comment by sinetris** [comment]
Hi @elpddev, 
There are a lot of things that I should change, but I think I will stop working on this project given that thoughtbot created an Elixir version of Factory Girl that is really nice (and is what I'm now using in my projects): https://github.com/thoughtbot/ex_machina

**Comment by elpddev** [comment]
Ok, thanks for the prompt reply.
